#
# SPDX-FileCopyrightText: Â© 2020-2023 Serpent OS Developers
#
# SPDX-License-Identifier: Zlib
#
name        : docker
version     : 23.0.4
release     : 5
homepage    : https://www.docker.com
upstreams   :
    - https://github.com/docker/cli/archive/refs/tags/v23.0.4.tar.gz : 477c37f128db7bb6926dc410f337cb525af4f26ea9719d38dc2978460dbe2de8
summary     : The open-source application container engine
description : |
    The open-source application container engine. This contains the docker cli.
license     :
    - Apache-2.0
networking  : yes
builddeps   :
    - binary(go)
    - binary(go-md2man)
rundeps     :
    - binary(dockerd)
    - docker-buildx
    - docker-compose
    - docker-scan
environment : |
    export GO111MODULE=auto
    # This can probably be removed after golang reboostrap.
    export GOMODCACHE="%(workdir)/.cache"

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"

    # Git commit corresponding to the version tag
    export GITCOMMIT="f480fb1e374b16c8a1419e84f465f2562456145e"
    export DOCKER_GITCOMMIT=$GITCOMMIT

    # Docker is meant to be built inside a container and will exit with an error if this isn't set.
    export DISABLE_WARN_OUTSIDE_CONTAINER=1

    # https://github.com/serpent-os/boulder/issues/74
    export CGO_CFLAGS="${CGO_CFLAGS} -Wno-error=unused-command-line-argument"
setup       : |
    mkdir -p src/github.com/docker/
    ln -s `pwd` src/github.com/docker/cli
build      : |
    cd src/github.com/docker/cli
    export GOPATH=`pwd`
    
    # docker-cli
    PLATFORM="Docker Engine - Community" \
    VERSION=%(version) \
        %make dynbinary
    
    # man pages
    make manpages
install    : |
    # docker-cli
    %install_exe build/docker-linux-amd64 %(installroot)/%(bindir)/docker

    # man pages
    %install_file man/man1/*.1 -t %(installroot)/%(mandir)/man1
    %install_file man/man5/*.5 -t %(installroot)/%(mandir)/man5

    # completions
    %install_file contrib/completion/bash/docker %(installroot)/%(completionsdir)/docker
    %install_file contrib/completion/zsh/_docker %(installroot)/%(datadir)/zsh/site-functions/_docker
    %install_file contrib/completion/fish/docker.fish %(installroot)/%(datadir)/fish/vendor_completions.d/docker.fish

    # nano dockerfile syntax highlighting
    %install_file %(pkgdir)/Dockerfile.nanorc -t %(installroot)/%(datadir)/nano/
