#
# SPDX-FileCopyrightText: Â© 2020-2024 Serpent OS Developers
#
# SPDX-License-Identifier: MPL-2.0
#
name        : docker-compose
version     : 2.17.3
release     : 4
homepage    : https://github.com/docker/compose
upstreams   :
    - https://github.com/docker/compose/archive/refs/tags/v2.17.3.tar.gz : e5e9bdfc3a827240381b656da88f92b408ea2e203c3f8cfd9e0bbfe03f825f16
summary     : Define and run multi-container applications with Docker 
description : |
    Define and run multi-container applications with Docker 
license     :
    - Apache-2.0
networking  : yes
builddeps   :
    - binary(go)
environment : |
    export _compose_r=github.com/docker/compose
    export _cli_plugins_dir=%(libdir)/docker/cli-plugins
    export GO111MODULE=auto

    # This can probably be removed after golang reboostrap.
    export GOMODCACHE="%(workdir)/.cache"

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external -ldflags=-X=$_compose_r/v2/internal.Version=v%(version)"

    # Git commit corresponding to the version tag
    export GITCOMMIT="7b0ed13209894b5981608f7d9e329a3a58af957d"
    
    # https://github.com/serpent-os/boulder/issues/74
    export CGO_CFLAGS="${CFLAGS} -Wno-error=unused-command-line-argument"
build      : |
    go build -o docker-compose ./cmd/compose
install    : |
    %install_exe docker-compose -t %(installroot)/$_cli_plugins_dir
